Include"Init.bb"
Include"Pack.bb"
Include"Math.bb"
Include"Ghost.bb"
Include"Maps.bb"
Include"Shadow.bb"
Include"Player.bb"
Include"Ground.bb"
Include"Wall.bb"
Include"Tree.bb"
Include"Mine.bb"
Include"Millitoid.bb"
Include"Hoverdroid.bb"
Include"Bouncer.bb"
Include"Cam.bb"
Include"CTRL.bb"
Include"Game.bb"

;~IDEal Editor Parameters:
;~C#Blitz3D